FROM ubuntu:22.04

RUN apt update && apt install -y \
    openssh-server sudo cron net-tools procps netcat-openbsd zsh xxd \
    && useradd -m -s /bin/zsh ctf && echo "ctf:ctf" | chpasswd

RUN mkdir /var/run/sshd

COPY reset_ctf.sh /usr/local/bin/reset_ctf.sh
COPY TASKs.txt /home/ctf/TASKs.txt
COPY setup.sh /setup.sh
RUN chmod +x /setup.sh && /setup.sh

EXPOSE 22
CMD ["/bin/bash", "-lc", "cron && nohup sh -c 'while true; do nc -l -p 9001 < /etc/service_flag.txt; done' >/dev/null 2>&1 & exec /usr/sbin/sshd -D"]
