FROM ubuntu:22.04

RUN apt update && apt install -y \
    openssh-server sudo cron net-tools procps \
    && useradd -m ctf && echo "ctf:ctf" | chpasswd

RUN mkdir /var/run/sshd

COPY reset_ctf.sh /usr/local/bin/reset_ctf.sh
COPY setup.sh /setup.sh
RUN chmod +x /setup.sh && /setup.sh

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
