networks:
  secnet:
    driver: bridge

volumes:
  elastic_data:

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.4
    container_name: elasticsearch
    networks: [secnet]
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:9.2.4
    container_name: kibana
    networks: [secnet]
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    restart: unless-stopped