FROM ghcr.io/playit-cloud/playit-agent:latest

ENV SECRET_KEY=${SECRET_KEY}

# The base image already has the correct ENTRYPOINT configured
# No need to override it


## docker run --rm -it \
##  --env-file .env \
##  playit-agent
